version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - auth
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - network

  auth:
    build:
      context: ./microservices/auth
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./microservices/auth:/app
    ports:
      - '3000:3000'
    networks:
      - network

networks:
  network:
    driver: bridge
