version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - auth

  auth:
    build:
      context: ./microservices/auth
      dockerfile: Dockerfile
    env_file:
      - ./.env
